(function(){
  const API_URL=(window.MONOROM_API_URL||'http://localhost:5000/api').replace(/\/$/,'');
  const ROOT_URL=new URL('./', document.currentScript && document.currentScript.src ? document.currentScript.src : location.href);
  const AUTH_KEY='monorom_auth'; const USER_KEY='monorom_user'; const LANG_KEY='monorom_lang';
  const EXEMPT=new Set([AUTH_KEY,USER_KEY,LANG_KEY,'monorom_active_user','monorom_admin_cache']);
  const rawGet=Storage.prototype.getItem, rawSet=Storage.prototype.setItem, rawRemove=Storage.prototype.removeItem, rawKey=Storage.prototype.key;
  let uid=null, syncing=false, initialized=false;
  const DB_NAME='monorom-offline-cache', DB_VER=1;
  function user(){try{return JSON.parse(rawGet.call(localStorage,USER_KEY)||'null')}catch{return null}}
  function token(){return rawGet.call(localStorage,AUTH_KEY)||''}
  function prefix(){return uid?'monorom_u_'+uid+'__':''}
  function scoped(k){return (uid && !EXEMPT.has(k))?prefix()+k:k}
  function initUid(){const u=user(); uid=u?.id||null}
  function idb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VER); r.onupgradeneeded=()=>{const db=r.result; if(!db.objectStoreNames.contains('kv'))db.createObjectStore('kv',{keyPath:'key'}); if(!db.objectStoreNames.contains('queue'))db.createObjectStore('queue',{keyPath:'id',autoIncrement:true})}; r.onsuccess=()=>resolve(r.result); r.onerror=()=>reject(r.error)})}
  async function cachePut(key,value,updatedAt){try{const db=await idb(); await new Promise((res,rej)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put({key,value,updatedAt});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}catch{}}
  async function queue(change){try{const db=await idb(); await new Promise((res,rej)=>{const tx=db.transaction('queue','readwrite');tx.objectStore('queue').add({...change,updatedAt:change.updatedAt||new Date().toISOString()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}catch{}}
  async function readQueue(){try{const db=await idb(); const out=await new Promise((res,rej)=>{const tx=db.transaction('queue','readonly');const q=tx.objectStore('queue').getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});db.close();return out}catch{return[]}}
  async function clearQueue(ids){if(!ids.length)return;try{const db=await idb();await new Promise((res,rej)=>{const tx=db.transaction('queue','readwrite'),s=tx.objectStore('queue');ids.forEach(id=>s.delete(id));tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}catch{}}
  function api(path,opts={}){return fetch(API_URL+path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{}),...(token()?{Authorization:'Bearer '+token()}: {})}}).then(async r=>{let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d})}
  function writeLocal(k,v){syncing=true; try{ if(v===undefined) rawRemove.call(localStorage,scoped(k)); else rawSet.call(localStorage,scoped(k),typeof v==='string'?v:JSON.stringify(v)); } finally{syncing=false;}}
  function snapshot(){const arr=[]; if(!uid)return arr; const p=prefix(); for(let i=0;i<localStorage.length;i++){const k=rawKey.call(localStorage,i); if(k&&k.startsWith(p)){const short=k.slice(p.length); const v=rawGet.call(localStorage,k); let parsed=v; try{parsed=JSON.parse(v)}catch{} arr.push({key:short,value:parsed,updatedAt:new Date().toISOString()})}} return arr;}
  async function push(){if(!navigator.onLine||!token()||!uid)return; const q=await readQueue(); const latest={}; q.forEach(x=>latest[x.key]=x); const changes=[...Object.values(latest)]; if(!changes.length)return; try{const result=await api('/sync/push',{method:'POST',body:JSON.stringify({changes,events:q.map(x=>({type:'data_change',data:{key:x.key,value:x.value},createdAt:x.updatedAt}))})}); const accepted=new Set(result.accepted||[]); await clearQueue(q.filter(x=>accepted.has(x.key)).map(x=>x.id)); await pull(false);}catch(e){console.warn('Monorom sync push deferred:',e.message)}}
  async function pull(showStatus=true){if(!navigator.onLine||!token()||!uid)return;try{const d=await api('/sync/pull'); syncing=true; for(const row of d.data||[]){if(row.value===null||row.value===undefined)rawRemove.call(localStorage,scoped(row.key));else rawSet.call(localStorage,scoped(row.key),typeof row.value==='string'?row.value:JSON.stringify(row.value)); await cachePut(row.key,row.value,row.updatedAt)} syncing=false; if(showStatus)status('online');}catch(e){syncing=false;status('offline');}}
  function status(mode){document.documentElement.dataset.monoromConnection=mode; const el=document.querySelector('[data-monorom-status]'); if(el)el.textContent=mode==='online'?'● Online':'● Offline';}
  async function migrateLegacy(){if(!uid)return; const keys=['routine_appointments','routine_activities','routine_water','routine_med_slots','routine_report','routine_activities_day','routine_med_day','family_contacts','doctor_contacts','ball_sort_best','seven_sister_best','void_breach_best','gentle_snake_best']; syncing=true; try{for(const k of keys){const old=rawGet.call(localStorage,k), neu=rawGet.call(localStorage,scoped(k));if(old!==null&&neu===null){rawSet.call(localStorage,scoped(k),old);rawRemove.call(localStorage,k)}}}finally{syncing=false}}
  function installStorageScope(){initUid(); if(!uid||initialized)return; initialized=true; for(const [name,fn] of [['getItem',function(k){return rawGet.call(this,scoped(k))}],['setItem',function(k,v){const sk=scoped(k); const ret=rawSet.call(this,sk,v); if(!syncing&&this===localStorage&&uid&&!EXEMPT.has(k)){const parsed=(()=>{try{return JSON.parse(v)}catch{return v}})(); cachePut(k,parsed,new Date().toISOString()); queue({key:k,value:parsed,updatedAt:new Date().toISOString()});}}],['removeItem',function(k){const sk=scoped(k); const ret=rawRemove.call(this,sk); if(!syncing&&this===localStorage&&uid&&!EXEMPT.has(k)){queue({key:k,value:null,updatedAt:new Date().toISOString()});} return ret}]]) Storage.prototype[name]=fn;
    migrateLegacy();
  }
  window.MonoromAPI={url:API_URL,api,user:()=>user(),token,logout(){rawRemove.call(localStorage,AUTH_KEY);rawRemove.call(localStorage,USER_KEY);location.href='login.html'},setLanguage(lang){rawSet.call(localStorage,LANG_KEY,lang);document.documentElement.lang=lang;},sync:push,pull};
  initUid(); installStorageScope();
  window.addEventListener('online',()=>{status('online');push();pull(false)}); window.addEventListener('offline',()=>status('offline'));
  document.addEventListener('DOMContentLoaded',async()=>{initUid(); if(location.pathname.endsWith('/login.html')||location.pathname.endsWith('/admin.html')){status(navigator.onLine?'online':'offline');return;} if(!token()||!uid){location.href='login.html';return;} installStorageScope(); status(navigator.onLine?'online':'offline'); if(navigator.onLine){await pull(false);await push();} setInterval(()=>{if(navigator.onLine)push()},15000); if('serviceWorker' in navigator) navigator.serviceWorker.register(new URL('service-worker.js',ROOT_URL)).catch(()=>{});});
})();
